server:
  port: 8000
spring:
  redis:
    host: 121.37.243.191
    port: 6379
    password: # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    database: 0 # Redis 数据库号，默认为 0 。
    timeout: 0 # Redis 连接超时时间，单位：毫秒。
    # 对应 RedisProperties.Jedis 内部类
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
        max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
        min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.3.60:3306/tortoise?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yqxdfs423
  application:
    name: nacos-gateway
  #config:
    #import: nacos:application.yml
  cloud:
    #nacos:
      #server-addr: 43.139.3.60:8848
    gateway:
      routes:
      - id: zk
        uri: lb://load-balanced-service
        predicates:
          - Path=/zk/**
        filters:
          - StripPrefix=1
    discovery:
      client:
        simple:
          instances:
            load-balanced-service:
              - uri: http://43.139.3.60:8003