server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.3.60:3306/fund?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  application:
    name: nacos-gateway
  config:
    import: nacos:application.yml
  cloud:
    nacos:
      server-addr: 43.139.3.60:8848
    gateway:
      routes:
      - id: zk
        uri: lb://load-balanced-service
        predicates:
          - Path=/zk/**
        filters:
          - StripPrefix=1
    discovery:
      client:
        simple:
          instances:
            load-balanced-service:
              - uri: http://localhost:8001
              - uri: http://localhost:8002
              - uri: http://localhost:8003