server:
  port: 8000
spring:
  application:
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://43.139.3.60:8848/
    gateway:
      routes:
      - id: zk
        uri: lb://load-balanced-service
        predicates:
          - Path=/zk/**
        filters:
          - StripPrefix=1
    discovery:
      client:
        simple:
          instances:
            load-balanced-service:
              - uri: http://localhost:8001
              - uri: http://localhost:8002
              - uri: http://localhost:8003